# Generated by Django 6.0.4 on 2026-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anchor_url', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('celebrity_url', models.CharField(max_length=200)),
                ('celebrity_name', models.CharField(max_length=50)),
                ('celebrity_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTheater',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NewLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_alt', models.CharField(max_length=100)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_src', models.CharField(max_length=200)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('anchor_class', models.CharField(max_length=2)),
                ('icon_class', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trailer_URL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrailerItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_src', models.CharField(max_length=200)),
                ('img_alt', models.CharField(max_length=100)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
