# Generated by Django 6.0.4 on 2026-04-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewLetter',
        ),
    ]
